[project]
name = "opsboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "snushev", email = "snushev@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.19.2",
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.141.1",
    "pydantic>=2.13.5",
    "sqlalchemy>=2.0.52",
    "uvicorn[standard]>=0.52.4",
]

[project.scripts]
opsboard = "opsboard:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
